### ISSUE TITLE
Give credit

### ISSUE THREAD

**Issue by legoboy0215** [RTGNetworkkk/Pets#1]
Don't claim something you didn't code *fully* as yours. This is a LBSG plugin...
https://github.com/Hydreon/LBPets

**Comment by RTGNetworkkk** [comment]
How! My version has a better ClearLag implementation, Mobs Clearing, newer pets, new commands, little rewrite of PetComand.php. I haven't update my Main and PetCommand yet. I'm currently adding the pets files first before I commit the Main and PetCommand. I'll leave a credit for LBPets and DriesBoy. Thanks for the call.

**Comment by legoboy0215** [comment]
Thank you :)
